In [246]:
import pandas as pd
import cmath
import numpy as np

In [247]:
df = pd.read_csv('file/bunga_iris.csv')

df.columns

x = df[['a1', 'a2', 'a3', 'a4']].values
y = df['label'].values

In [248]:
x

array([[7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.3, 2.8, 5.1, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 2. , 3.5, 1. ],
       [5. , 3.2, 1.2, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [7.1, 3. , 5.9, 2.1],
       [6. , 3. , 4.8, 1.8],
       [6.8, 2.8, 4.8, 1.4],
       [5.7, 2.9, 4.2, 1.3],
       [6. , 2.2, 4. , 1. ],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.5, 1.4, 0.2],
       [5.5, 4.2, 1.4, 0.2]])

In [249]:
y

array([0, 0, 0, 2, 2, 1, 1, 0, 0, 2, 2, 2, 1, 1, 0, 0, 2, 2, 1, 1, 1],
      dtype=int64)

In [250]:
x_train = x[:15]
y_train = y[:15]
x_test = x[15:21]
y_test = y[15:21]

x_test

array([[6.5, 3. , 5.5, 1.8],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.5, 1.4, 0.2],
       [5.5, 4.2, 1.4, 0.2]])

# KNN Using sklearn

In [251]:
from sklearn.neighbors import KNeighborsClassifier as KNC

knn = KNC(n_neighbors=7).fit(x_train,y_train)
yhat = knn.predict(x_test)
yhat

array([0, 2, 2, 1, 1, 1], dtype=int64)

In [252]:
from sklearn import metrics
print("Train Accuracy : ", metrics.accuracy_score(y_train, knn.predict(x_train)))
print("Test Accuracy : ", metrics.accuracy_score(y_test, knn.predict(x_test)))

Train Accuracy :  0.9333333333333333
Test Accuracy :  1.0
