In [58]:
import itertools
import numpy as np
import matplotlib.ticker as ticker
from matplotlib.ticker import NullFormatter
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import datasets
%matplotlib inline

In [59]:
outlook = ['Sunny', 'Sunny', 'Overcast', 'Rainly','Rainly','Rainly', 'Overcast', 'Sunny','Sunny','Rainly','Sunny','Overcast', 'Rainly', 'Rainly']
temp = ['Hot','Hot','Hot', 'Mild', 'Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
humidity = ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal', 'High', 'Normal', 'High']
windy = ['False', 'True','False','False','False','True','True','False','False','False','True','True','False','True']
play = ['No','No', 'Yes','Yes','Yes','No', 'Yes','No', 'Yes','Yes', 'Yes','Yes', 'Yes','No']

In [60]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

outlook_encoded = le.fit_transform(outlook)
temp_encode = le.fit_transform(temp)
humidity_encode = le.fit_transform(humidity)
windy_encode = le.fit_transform(windy)
label = le.fit_transform(play)




In [61]:
print(outlook_encoded)
print(temp_encode)
print(humidity_encode)
print(windy_encode)
print(label)


[2 2 0 1 1 1 0 2 2 1 2 0 1 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[0 1 0 0 0 1 1 0 0 0 1 1 0 1]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [62]:
features = np.column_stack([outlook_encoded,temp_encode,humidity_encode,windy_encode])
features

array([[2, 1, 0, 0],
       [2, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 1],
       [2, 2, 0, 0],
       [2, 0, 1, 0],
       [1, 2, 1, 0],
       [2, 2, 1, 1],
       [0, 2, 0, 1],
       [1, 1, 1, 0],
       [1, 2, 0, 1]], dtype=int64)

In [63]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(features,label)
pred = model.predict([[2,1,0,1]])
print('Predicted Value =',pred)

Predicted Value = [0]
